- name: Install Apache.
  hosts: web
  become: yes
  gather_facts: no

  vars:
    apache_package_name: httpd
    apache_service_name: httpd.service

  tasks:
    - name: Install the httpd package.
      ansible.builtin.yum:
        name: "{{ apache_package_name }}"
        state: present
      notify:
        - start apache service

    - name: Install the firewalld package.
      ansible.builtin.yum:
        name: firewalld
        state: present

    - name: Start "firewalld.service".
      ansible.builtin.systemd:
        name: firewalld.service
        enabled: yes
        state: started

  handlers:
    - name: Change the listening port.
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: "^Listen "
        line: "Listen 8080"
        validate: httpd -t -f %s
      listen:
        - start apache service

    - name: Start "httpd.service".
      ansible.builtin.systemd:
        name: "{{ apache_service_name }}"
        enabled: yes
        state: started
      listen:
        - start apache service

    - name: Drill a hole for the http port.
      ansible.posix.firewalld:
        port: "{{ http_port }}/tcp"
        permanent: yes
        immediate: yes
        state: enabled
      listen:
        - start apache service
